name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Get your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Java (required for Android build)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          cache: true

      # 4. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 5. Clean project (VERY important)
      - name: Clean build
        run: flutter clean

      # 6. Build APK
      - name: Build APK
        run: flutter build apk --release

      # 7. Upload APK file
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk